export const AVIABLE_CARD = 0;
export const PLAYER_1 = 1;
export const PLAYER_2 = 2;

export const UNIQUE_CARDS = [
  { label: "CAP ALPHA", icon: "\u0391" },
  { label: "CAP BETA", icon: "\u0392" },
  { label: "CAP GAMMA", icon: "\u0393" },
  { label: "CAP DELTA", icon: "\u0394" },
  { label: "CAP EPSILON", icon: "\u0395" },
  { label: "CAP ZETA", icon: "\u0396" },
  { label: "ALPHA", icon: "\u03B1" },
  { label: "BETA", icon: "\u03B2" },
  { label: "GAMMA", icon: "\u03B3" },
  { label: "DELTA", icon: "\u03B4" },
  { label: "EPSILON", icon: "\u03B5" },
  { label: "ZETA", icon: "\u03B6" },
  { label: "ETA", icon: "\u03B7" },
  { label: "THETA", icon: "\u03B8" },
  { label: "IOTA", icon: "\u03B9" },
  { label: "KAPPA", icon: "\u03BA" },
  { label: "LAMBDA", icon: "\u03BB" },
  { label: "MU", icon: "\u03BC" },
  { label: "NU", icon: "\u03BD" },
  { label: "XI", icon: "\u03BE" },
  { label: "OMICRON", icon: "\u03BF" },
  { label: "PI", icon: "\u03C0" },
  { label: "RHO", icon: "\u03C1" },
  { label: "SIGMA", icon: "\u03C3" },
  { label: "TAU", icon: "\u03C4" },
  { label: "UPSILON", icon: "\u03C5" },
  { label: "PHI", icon: "\u03C6" },
  { label: "CHI", icon: "\u03C7" },
  { label: "PSI", icon: "\u03C8" },
  { label: "OMEGA", icon: "\u03C9" },
];
